"""Provider-neutral model adapter contracts and deterministic test doubles."""

from rag_providers.contracts import (
    EmbeddingAdapter,
    EmbeddingRequest,
    EmbeddingResult,
    GenerationAdapter,
    GenerationComplete,
    GenerationDelta,
    GenerationEvent,
    GenerationRequest,
    GenerationResult,
    ProviderAdapterError,
    ProviderCapabilities,
    ProviderErrorCode,
    ProviderResultMetadata,
    ProviderRole,
    RequestBudget,
    RerankAdapter,
    RerankRequest,
    RerankResult,
    RewriteAdapter,
    RewriteRequest,
    RewriteResult,
    TokenUsage,
)
from rag_providers.fakes import FakeEmbeddingAdapter, FakeGenerationAdapter
from rag_providers.orchestration import ProviderOrchestrator

__all__ = [
    "EmbeddingAdapter",
    "EmbeddingRequest",
    "EmbeddingResult",
    "FakeEmbeddingAdapter",
    "FakeGenerationAdapter",
    "GenerationAdapter",
    "GenerationComplete",
    "GenerationDelta",
    "GenerationEvent",
    "GenerationRequest",
    "GenerationResult",
    "ProviderAdapterError",
    "ProviderCapabilities",
    "ProviderErrorCode",
    "ProviderOrchestrator",
    "ProviderResultMetadata",
    "ProviderRole",
    "RerankAdapter",
    "RerankRequest",
    "RerankResult",
    "RequestBudget",
    "RewriteAdapter",
    "RewriteRequest",
    "RewriteResult",
    "TokenUsage",
]
