[project]
name = "rag-support-api"
version = "0.0.0"
requires-python = "==3.13.*"
dependencies = []

[project.optional-dependencies]
api = [
    "fastapi[standard-no-fastapi-cloud-cli]==0.141.1",
]
migrations = [
    "alembic==1.18.5",
    "cloud-sql-python-connector[pg8000]==1.21.0",
    "pg8000==1.31.5",
    "sqlalchemy==2.0.51",
]

[tool.uv]
package = false

[tool.fastapi]
entrypoint = "rag_api.main:app"
